[nimib]
srcDir = "book"
homeDir = "docs"

[nimibook]
title = "SciNim Getting Started"
description = "Tutorials for libraries in SciNim ecosystems"
git_repository_url = "https://github.com/SciNim/getting-started"
plausible_analytics_url = "scinim.github.io/getting-started"
