name: valid

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install scipy numpy
      - name: "install_nim"
        id: install_nim
        uses: iffy/install-nim@v4.1.1
      - run: nimble install -y
      - name: GenBook
        run: nimble genbook
      - run: echo Commit hash = ${{ github.event.pull_request.head.sha }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ github.event.pull_request.head.sha }}
          path: docs/
          retention-days: 1
          if-no-files-found: error
